/*
* Problem Description : A Guessing game in which user gets 10 tries to giess a random number generated by program,
*                       He is assisted by various messages printed by program to get closer to the answer.
*
* Author : Anmol Singh
* Date : 23rd jan 2019
*
* Pseudocode : String one is taken as input, (one).
*               String two is taken as input, (two).
*               if they areAnagrams() - function is called to check whether they are anagrams
*                   then print "Given Strings are Anagrams."
*               else
*                   print "Given Strings are not Anagrams."
*
*               areAnagrams function starts here....
*                   areAnagrams(String first, String second)
*                   Both Strings converted to character Arrays
*                   Both Strings then sorted by characters
*                   Both Strings are then checked whether they are equal or not
*                   if equal
*                       return true
*                   else 
*                       return false
*               areAnagrams function ends here....
*/

import java.util.*;

public class Anagram_M3
{
    public static boolean areAnagrams(String first, String second)
    {
        char one[] = first.toCharArray();
        char two[] = second.toCharArray();


        Arrays.sort(one);
        Arrays.sort(two);

        System.out.println();
        System.out.println();

        return Arrays.equals(one, two);
    }

    public static void main(String [] args)
    {
        Scanner in =new Scanner(System.in);
        String one = "";
        String two = "";

        System.out.println("Enter First word : ");
        one = in.next();

        System.out.println("Enter Second word: ");
        two = in.next();

        if(areAnagrams(one.toLowerCase(),two.toLowerCase()))
            System.out.println("Given Strings are Anagrams.");

        else
            System.out.println("Given Strings are not Anagrams");
    }
}