/*
* Problem Description : A Guessing game in which user gets 10 tries to giess a random number generated by program,
*                       He is assisted by various messages printed by program to get closer to the answer.
*
* Author : Anmol Singh
* Date : 23rd jan 2019
*
* Pseudocode : Introduction messages are printed, regarding the rules of the game.
*               
*               'result' is the random number generated between 1 to 100 by computer.
*               Input variable 'inp' (Integer)
*               character array 'choice' used to take users input to start the game or not(y/n || Y/N)
*               
*               if choice[0] is equal to 'n'
*                   then exit the game, and Print "You are Out of Game Now....."
*               
*               else
*                   while(choice[0] is equal to 'y') do
*                       print number of tries taken by user
*                       take inp as input of user
*                       
*                           check if the number entered is close to the result or not by using check(inp, result) function
*                           check function starts.....
*                               if inp is greater than result
*                                   print "You are Close to the answer!! Try Again with a lesser number."
*                               
*                               else if inp is less than result
*                                   print "You are Close to the answer!! Try Again with a larger number."
*                               
*                               else if inp is equal to result
*                                   print "You Guessed the correct answer!! You won!!"
*                               
*                               else for any other case
*                                   print "You are too far from the Answer!! Try again"
*                           check function ends.......
*                   end while 
*/

//Code Here...
import java.util.*;

public class GuessingGame_M1
{
    //Guessing Game
    public static void main(String args[])
    {
        
        Scanner in = new Scanner(System.in);
        
        //Starting Statements for User Convinience
        System.out.println("You are Welcome to Guessing Game....!!!");
        System.out.println("Rules: ");
        System.out.println("You have to Guess a random Integer between 0 to 100 in your mind and enter it as Input. We will tell you if your number is too large are too small from the answer.");
        System.out.println("You have to Guess the correct number in at most 10 tries");
        
        //Random number generated
        Random rand = new Random();

        int result = rand.nextInt(100) + 1;

        int inp;
        char choice[];
        String ch;
        int numberOfTries = 0;
        
        System.out.println("Start Game? y/n");
        ch = in.next();
        choice = ch.toCharArray();
        
        if(choice[0] == 'n' || choice[0] == 'N')
        {   
            System.out.println("You are Out of the Game Now....");
        }
        
        else
        {
            do 
            {            
                System.out.println("Number of Tries Finished : "+numberOfTries);
                System.out.println("Enter an Integer : ");
                inp = in.nextInt();
                check(inp, result);// Checks whether the user is too close or too far from the answer and prompts with a message on terminal
                    
                //10 tries and you are out of game
                if(numberOfTries == 10 )
                {
                    System.out.println("You Used all 10 Tries!! You Lost.");
                    break;
                }

                else if(inp == result)
                    break;
                
                //Number of tries calculator
                numberOfTries++;            
            }while(choice[0] == 'y' || choice[0] == 'Y');
        }
    }

    public static void check(int inp, int result)
    {

        if(inp > result)
        {
            System.out.println("You are Close to the answer!! Try Again with a lesser number.");
        }

        else if(inp < result )
        {
            System.out.println("You are Close to the answer!! Try Again with a larger number.");    
        }

        else if(inp == result)
        { 
            System.out.println("You Guessed the correct answer!! You won!!");    
        }

        else
        {
            System.out.println("You are too far from the Answer!! Try again");
        }
    }
}